In [11]:
import numpy as np

#1
a = np.linspace(1, 10, num=10)
print(a)

#2
b = np.zeros((3, 3), dtype=int)
print(b)

#3
#c = np.random.random((5 ,5),)
#c = np.random.integers(10, size=(5, 5))
#c = np.random.integers(1, high=10, size=(5, 5))
#c = np.empty([5, 5], dtype=int)
c = np.random.randint(1, 11, size=(5, 5))
print(c)

#4
d = np.random.random((4 ,4))
print(d)

#5
e1 = np.random.randint(1, 11, size=5)
e2 = np.random.randint(1, 11, size=5)
e3 = e1+e2
e4 = e1-e2
e5 = e1*e2

#6
f1 = np.random.random(7)
f2 = np.random.random(7)
f = np.dot(f1, f2)

#7
g1 = np.random.randint(1, 11, size=(2, 2))
g2 = np.random.randint(1, 11, size=(2, 3))
g = np.dot(g1, g2)

#8
i = np.random.randint(1, 11, size=(3, 3))
i_inv = np.linalg.inv(i)

#9
j = np.random.random((4, 4))
jt = j.T

#10
k1 = np.random.randint(1, 11, size=(3, 4))
k2 = np.random.randint(1, 11, size=4)
k = np.dot(k1, k2)

#11
l1 = np.random.random((2, 3))
l2 = np.random.random(3)
l = np.dot(l1, l2)

#12
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))
m = m1 * m2

#13
n1 = np.random.randint(1, 11, (2, 2))
n2 = np.random.randint(1, 11, (2, 2))
n = np.dot(n1, n2)

#14
o = np.random.randint(1, 101, (5, 5))
o.sum()

#15
p1 = np.random.randint(1, 11, (4, 4))
p2 = np.random.randint(1, 11, (4, 4))
p1 - p2

#16 не знайшов простого метода
# тому спочатку транспонував матрицю, потів підсумував стовпчики і обернув на стовпчик з сумою рядків вихідної матриці
q = np.random.random((3, 3))
qt= q.T
qts = sum(qt)
q1 = qts.reshape((3, 1))
print(q1)

#17
r = np.random.randint(100, size=(3, 4)) #не знайшов як вибрати випадкове ціле число без зазначення діапазону
print(r)
r1 = np.power(r, 2)
print(r1)

#18
t = np.random.randint(1, 51, 4)
print(t)
t1 = np.sqrt(t)
print(t1)



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 9  8  4  9  4]
 [ 3  4  4  7  3]
 [10  9  6  4  4]
 [ 8  2  5  8  5]
 [ 8  2  9  5  4]]
[[0.30302745 0.14803315 0.78954191 0.067923  ]
 [0.10820462 0.68436891 0.47484219 0.33141613]
 [0.52553219 0.99809152 0.84097043 0.51631002]
 [0.85449607 0.09669179 0.74809165 0.34716269]]
[[0.30807036]
 [1.61956559]
 [2.28904076]]
[[27 81 30 80]
 [48 33 10 80]
 [83 80 32 71]]
[[ 729 6561  900 6400]
 [2304 1089  100 6400]
 [6889 6400 1024 5041]]
[29 40 37 15]
[5.38516481 6.32455532 6.08276253 3.87298335]
